(package "vsc-multiple-cursors"
         "0.1.0"
         "multiple-curosrs integration behave like VSCode")

(website-url "https://github.com/emacs-vs/vsc-multiple-cursors")
(keywords "convenience" "vscode" "vsc" "multiple-cursors")

(package-file "vsc-multiple-cursors.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "multiple-cursors")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
